# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/carlocolli/Desktop/projects/Tesi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/carlocolli/Desktop/projects/Tesi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carlocolli/Desktop/projects/Tesi/CMakeFiles /Users/carlocolli/Desktop/projects/Tesi//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carlocolli/Desktop/projects/Tesi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GNSSlibrary

# Build rule for target.
GNSSlibrary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GNSSlibrary
.PHONY : GNSSlibrary

# fast build rule for target.
GNSSlibrary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/build
.PHONY : GNSSlibrary/fast

#=============================================================================
# Target rules for targets named velocityTest

# Build rule for target.
velocityTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 velocityTest
.PHONY : velocityTest

# fast build rule for target.
velocityTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/build
.PHONY : velocityTest/fast

#=============================================================================
# Target rules for targets named rinex

# Build rule for target.
rinex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rinex
.PHONY : rinex

# fast build rule for target.
rinex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/build
.PHONY : rinex/fast

#=============================================================================
# Target rules for targets named preciseEph

# Build rule for target.
preciseEph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preciseEph
.PHONY : preciseEph

# fast build rule for target.
preciseEph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/build
.PHONY : preciseEph/fast

#=============================================================================
# Target rules for targets named atmoMain

# Build rule for target.
atmoMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 atmoMain
.PHONY : atmoMain

# fast build rule for target.
atmoMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/build
.PHONY : atmoMain/fast

scripts/core.o: scripts/core.cpp.o
.PHONY : scripts/core.o

# target to build an object file
scripts/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/scripts/core.cpp.o
.PHONY : scripts/core.cpp.o

scripts/core.i: scripts/core.cpp.i
.PHONY : scripts/core.i

# target to preprocess a source file
scripts/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/scripts/core.cpp.i
.PHONY : scripts/core.cpp.i

scripts/core.s: scripts/core.cpp.s
.PHONY : scripts/core.s

# target to generate assembly for a file
scripts/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/scripts/core.cpp.s
.PHONY : scripts/core.cpp.s

scripts/main.o: scripts/main.cpp.o
.PHONY : scripts/main.o

# target to build an object file
scripts/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/scripts/main.cpp.o
.PHONY : scripts/main.cpp.o

scripts/main.i: scripts/main.cpp.i
.PHONY : scripts/main.i

# target to preprocess a source file
scripts/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/scripts/main.cpp.i
.PHONY : scripts/main.cpp.i

scripts/main.s: scripts/main.cpp.s
.PHONY : scripts/main.s

# target to generate assembly for a file
scripts/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/scripts/main.cpp.s
.PHONY : scripts/main.cpp.s

scripts/velocityTest.o: scripts/velocityTest.cpp.o
.PHONY : scripts/velocityTest.o

# target to build an object file
scripts/velocityTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/scripts/velocityTest.cpp.o
.PHONY : scripts/velocityTest.cpp.o

scripts/velocityTest.i: scripts/velocityTest.cpp.i
.PHONY : scripts/velocityTest.i

# target to preprocess a source file
scripts/velocityTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/scripts/velocityTest.cpp.i
.PHONY : scripts/velocityTest.cpp.i

scripts/velocityTest.s: scripts/velocityTest.cpp.s
.PHONY : scripts/velocityTest.s

# target to generate assembly for a file
scripts/velocityTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/scripts/velocityTest.cpp.s
.PHONY : scripts/velocityTest.cpp.s

src/GNSSlibrary/atmo.o: src/GNSSlibrary/atmo.cpp.o
.PHONY : src/GNSSlibrary/atmo.o

# target to build an object file
src/GNSSlibrary/atmo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/atmo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/atmo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/src/GNSSlibrary/atmo.cpp.o
.PHONY : src/GNSSlibrary/atmo.cpp.o

src/GNSSlibrary/atmo.i: src/GNSSlibrary/atmo.cpp.i
.PHONY : src/GNSSlibrary/atmo.i

# target to preprocess a source file
src/GNSSlibrary/atmo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/atmo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/atmo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/src/GNSSlibrary/atmo.cpp.i
.PHONY : src/GNSSlibrary/atmo.cpp.i

src/GNSSlibrary/atmo.s: src/GNSSlibrary/atmo.cpp.s
.PHONY : src/GNSSlibrary/atmo.s

# target to generate assembly for a file
src/GNSSlibrary/atmo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/atmo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/atmo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/src/GNSSlibrary/atmo.cpp.s
.PHONY : src/GNSSlibrary/atmo.cpp.s

src/GNSSlibrary/broadcastEph.o: src/GNSSlibrary/broadcastEph.cpp.o
.PHONY : src/GNSSlibrary/broadcastEph.o

# target to build an object file
src/GNSSlibrary/broadcastEph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/broadcastEph.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/broadcastEph.cpp.o
.PHONY : src/GNSSlibrary/broadcastEph.cpp.o

src/GNSSlibrary/broadcastEph.i: src/GNSSlibrary/broadcastEph.cpp.i
.PHONY : src/GNSSlibrary/broadcastEph.i

# target to preprocess a source file
src/GNSSlibrary/broadcastEph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/broadcastEph.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/broadcastEph.cpp.i
.PHONY : src/GNSSlibrary/broadcastEph.cpp.i

src/GNSSlibrary/broadcastEph.s: src/GNSSlibrary/broadcastEph.cpp.s
.PHONY : src/GNSSlibrary/broadcastEph.s

# target to generate assembly for a file
src/GNSSlibrary/broadcastEph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/broadcastEph.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/broadcastEph.cpp.s
.PHONY : src/GNSSlibrary/broadcastEph.cpp.s

src/GNSSlibrary/coresky.o: src/GNSSlibrary/coresky.cpp.o
.PHONY : src/GNSSlibrary/coresky.o

# target to build an object file
src/GNSSlibrary/coresky.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/coresky.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/coresky.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/src/GNSSlibrary/coresky.cpp.o
.PHONY : src/GNSSlibrary/coresky.cpp.o

src/GNSSlibrary/coresky.i: src/GNSSlibrary/coresky.cpp.i
.PHONY : src/GNSSlibrary/coresky.i

# target to preprocess a source file
src/GNSSlibrary/coresky.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/coresky.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/coresky.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/src/GNSSlibrary/coresky.cpp.i
.PHONY : src/GNSSlibrary/coresky.cpp.i

src/GNSSlibrary/coresky.s: src/GNSSlibrary/coresky.cpp.s
.PHONY : src/GNSSlibrary/coresky.s

# target to generate assembly for a file
src/GNSSlibrary/coresky.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/coresky.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/coresky.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/src/GNSSlibrary/coresky.cpp.s
.PHONY : src/GNSSlibrary/coresky.cpp.s

src/GNSSlibrary/rinex3Nav.o: src/GNSSlibrary/rinex3Nav.cpp.o
.PHONY : src/GNSSlibrary/rinex3Nav.o

# target to build an object file
src/GNSSlibrary/rinex3Nav.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/rinex3Nav.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/rinex3Nav.cpp.o
.PHONY : src/GNSSlibrary/rinex3Nav.cpp.o

src/GNSSlibrary/rinex3Nav.i: src/GNSSlibrary/rinex3Nav.cpp.i
.PHONY : src/GNSSlibrary/rinex3Nav.i

# target to preprocess a source file
src/GNSSlibrary/rinex3Nav.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/rinex3Nav.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/rinex3Nav.cpp.i
.PHONY : src/GNSSlibrary/rinex3Nav.cpp.i

src/GNSSlibrary/rinex3Nav.s: src/GNSSlibrary/rinex3Nav.cpp.s
.PHONY : src/GNSSlibrary/rinex3Nav.s

# target to generate assembly for a file
src/GNSSlibrary/rinex3Nav.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/rinex3Nav.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/rinex3Nav.cpp.s
.PHONY : src/GNSSlibrary/rinex3Nav.cpp.s

src/GNSSlibrary/utility.o: src/GNSSlibrary/utility.cpp.o
.PHONY : src/GNSSlibrary/utility.o

# target to build an object file
src/GNSSlibrary/utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/src/GNSSlibrary/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/src/GNSSlibrary/utility.cpp.o
.PHONY : src/GNSSlibrary/utility.cpp.o

src/GNSSlibrary/utility.i: src/GNSSlibrary/utility.cpp.i
.PHONY : src/GNSSlibrary/utility.i

# target to preprocess a source file
src/GNSSlibrary/utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/src/GNSSlibrary/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/src/GNSSlibrary/utility.cpp.i
.PHONY : src/GNSSlibrary/utility.cpp.i

src/GNSSlibrary/utility.s: src/GNSSlibrary/utility.cpp.s
.PHONY : src/GNSSlibrary/utility.s

# target to generate assembly for a file
src/GNSSlibrary/utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GNSSlibrary.dir/build.make CMakeFiles/GNSSlibrary.dir/src/GNSSlibrary/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/velocityTest.dir/build.make CMakeFiles/velocityTest.dir/src/GNSSlibrary/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rinex.dir/build.make CMakeFiles/rinex.dir/src/GNSSlibrary/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preciseEph.dir/build.make CMakeFiles/preciseEph.dir/src/GNSSlibrary/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/atmoMain.dir/build.make CMakeFiles/atmoMain.dir/src/GNSSlibrary/utility.cpp.s
.PHONY : src/GNSSlibrary/utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GNSSlibrary"
	@echo "... atmoMain"
	@echo "... preciseEph"
	@echo "... rinex"
	@echo "... velocityTest"
	@echo "... scripts/core.o"
	@echo "... scripts/core.i"
	@echo "... scripts/core.s"
	@echo "... scripts/main.o"
	@echo "... scripts/main.i"
	@echo "... scripts/main.s"
	@echo "... scripts/velocityTest.o"
	@echo "... scripts/velocityTest.i"
	@echo "... scripts/velocityTest.s"
	@echo "... src/GNSSlibrary/atmo.o"
	@echo "... src/GNSSlibrary/atmo.i"
	@echo "... src/GNSSlibrary/atmo.s"
	@echo "... src/GNSSlibrary/broadcastEph.o"
	@echo "... src/GNSSlibrary/broadcastEph.i"
	@echo "... src/GNSSlibrary/broadcastEph.s"
	@echo "... src/GNSSlibrary/coresky.o"
	@echo "... src/GNSSlibrary/coresky.i"
	@echo "... src/GNSSlibrary/coresky.s"
	@echo "... src/GNSSlibrary/rinex3Nav.o"
	@echo "... src/GNSSlibrary/rinex3Nav.i"
	@echo "... src/GNSSlibrary/rinex3Nav.s"
	@echo "... src/GNSSlibrary/utility.o"
	@echo "... src/GNSSlibrary/utility.i"
	@echo "... src/GNSSlibrary/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

